name: goodtables

on:
  schedule:
    - cron:  '0 1 * * *'
  pull_request:
    paths:
      - 'schema/*.csv'
      - 'datapackage.json'
  push:
    paths:
      - 'schema/*.csv'
      - 'datapackage.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run goodtables
      run: make docker-validate